### ISSUE TITLE
quite confused with the portal thing

### ISSUE THREAD

**Issue by uncomfyhalomacro** [mahkoh/jay#204]
aren't there supposed to be the following files :O

org.freedesktop.impl.portal.desktop.jay.service
```
[D-BUS Service]
Name=org.freedesktop.impl.portal.desktop.jay
Exec=/bin/false
SystemdService=xdg-desktop-portal-jay.service
```

xdg-desktop-portal-jay.service
```
[Unit]
Description=Portal (Jay wayland compositor)
PartOf=graphical-session.target
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Service]
Type=dbus
BusName=org.freedesktop.impl.portal.desktop.jay
ExecStart=/usr/bin/jay portal
Restart=on-failure
```

**Comment by mahkoh** [comment]
The portal is started automatically when you start Jay.

**Comment by uncomfyhalomacro** [comment]
ah that makes sense! thanks!

**Comment by uncomfyhalomacro** [comment]
seems it doesnt work after removing them. added them back. i am not familiar with the difference with "on-demand" portal. maybe a systemd thing or something

**Comment by mahkoh** [comment]
Please post the logs from .local/share/jay/logs/portal.

**Comment by uncomfyhalomacro** [comment]
> Please post the logs from ~/.local/share/jay/logs/portal.

Just going to tell that it might be because i haven't rebooted/quit-then-reopen jay because i installed the latest release while running the old jay. 

so it works now.
