### ISSUE TITLE
Feature: Variable refresh rate monitor support

### ISSUE THREAD

**Issue by tadeokondrak** [mahkoh/jay#214]
The DRM backend could support a variable refresh rate on monitors with support but it currently doesn't.

wlroots' implementation is [here](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/52c67284e25c6a31a260b4918132f7842e18532d).

**Comment by mahkoh** [comment]
I do not own a VRR monitor and VRR is unlikely to happen until that changes.

**Comment by mahkoh** [comment]
Please try #227.

**Comment by tadeokondrak** [comment]
Thank you! It's working perfectly.
