### ISSUE TITLE
xkb options (i.e., "caps:escape")

### ISSUE THREAD

**Issue by junelva** [mahkoh/jay#217]
I tried for a few hours to figure this out, but I was unable to. Is it possible to pass common xkb_options such as "caps:escape"?

**Comment by mahkoh** [comment]
Jay uses the most general form of xkb keymaps. Anything that is possible in other compositors should also be possible in Jay. You can find the full list of available options under `/usr/share/X11/xkb`.

What you probably want is

```toml
keymap = """
    xkb_keymap {
        xkb_keycodes { include "evdev+aliases(qwerty)" };
        xkb_types    { include "complete"              };
        xkb_compat   { include "complete"              };
        xkb_symbols  { include "pc+us+inet(evdev)+capslock(escape)"     };
    };
    """
```

**Comment by junelva** [comment]
Sadly, that did not work for me. I tried various other solutions inside of xkb share files to no avail. In the end what I have done is created a remapping using input-remapper-gtk, which I already use for mouse buttons. It would be nice to eventually not need that script, but for now it works.

By the way, thanks for your work on this compositor. It meets many of my needs so far.
