### ISSUE TITLE
10-bit output format

### ISSUE THREAD

**Issue by kennylevinsen** [mahkoh/jay#244]
Seems like XRGB8888 is hardcoded as the output format with no exposed configuration to switch to 10-bit.

**Comment by mahkoh** [comment]
I looked into this some time ago but I could not find anything in the EDID indicating that the output would profit from 10 bit colors. I already have code locally somewhere to allocate 10 bit framebuffers with fallback to 8.

**Comment by kennylevinsen** [comment]
The EDID does have a "bits per primary color channel" which reads 10 for my laptop panel. If no intermediate blending buffer is used, it can also help bending even if less than 10-bit panels are used.

In sway we have a per-output setting for enabling 10-bit, although with Vulkan we're going through an F16 intermediate buffer anyway. It's only our gles2 backend that rely on it for improved blending performance.

**Comment by mahkoh** [comment]
>In sway we have a per-output setting for enabling 10-bit

Such a setting would be easy to add I suppose.

**Comment by mahkoh** [comment]
I've implemented a manual setting in #253 but I'm unable to see any difference locally. Do you have an application where this would show up?

Downgrading to rgb565 does show an obvious difference.

**Comment by kennylevinsen** [comment]
Hmm, off the top of my head, https://git.sr.ht/~emersion/chayang (dims screen with a semitransparent layer surface using single_pixel_buffer) run as `chayang -d 20` has clear steps on my laptop's OLED display with an 8-bit render format on sway, much less so with 10-bit.

I imagine a subsurface with an alpha gradient would also be a good test, but don't have a test client for that handy.

**Comment by mahkoh** [comment]
I only have 8-bit panels (with fake HDR) but `chayang -d 20` showed a clear improvement with 10-bit formats nevertheless. Thanks.
