### ISSUE TITLE
(minor issue) connector type not recognised

### ISSUE THREAD

**Issue by nabajour** [mahkoh/jay#280]
Hi, 

I'm trying to get jay to work on my machine with these specs:
- os: Debian unstable
- graphics card: NVidia 2080 TI
- drivers: upstream nvidia drivers  560.35.03 (ubuntu packages from nvidia)
- 30" HDMI Monitor connected over an adapter to the USB-C output of the graphics card.

I'm building a shared library config, as I want to tinker with jay and use it to replace my XMonad WM. It looks like the USB-C connector is not recognised and gets named `Unknown(0)-1`. In the logs, I see this output:

```[2024-10-02T14:11:20.251Z ERROR jay::config::handler] /home/nab/src/jay/jay-config/src/video.rs:356: `Unknown(0)-1` is not a valid connector identifier```

and my `get_connector("Unknown(0)-1")` fails. I was able to work around it by matching the name and could then set the mode needed.

It looks like that `Unknown(0)-`  doesn't  match the expected `Unknown-` prefix in `video.rs`.

`xrandr` shows this connector as `USB-C-0`: 

```
$ xrandr
Screen 0: minimum 8 x 8, current 2560 x 1600, maximum 32767 x 32767
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
USB-C-0 connected primary 2560x1600+0+0 (normal left inverted right x axis y axis) 641mm x 401mm
   1280x800      59.91 +
   2560x1600     59.86*
```

I was wondering if there was a `DRM_MODE_CONNECTOR_<foo>`  mismatch, but that doesn't seem to be the case. But I'm neither a DRM, nor a rust expert. 

I was able to work around the issue, so this is probably a cosmetic problem. I still run into other issues, so I thought I'd report this here for reference.

**Comment by mahkoh** [comment]
The connector types are defined in https://github.com/torvalds/linux/blob/e32cde8d2bd7d251a8f9b434143977ddf13dcec6/include/uapi/drm/drm_mode.h#L403-L423 and they seem unchanged since I first copied them.

What's the output of `ls /sys/class/drm`?

**Comment by nabajour** [comment]
```
$ ls /sys/class/drm     
card0       card0-DP-2      card0-HDMI-A-2   renderD128
card0-DP-1  card0-HDMI-A-1  card0-Unknown-1  version
```

And just ran a test: `swaymsg -t get_outputs` also sees it as `Unknown-1`

**Comment by mahkoh** [comment]
Instead of `"Unknown-1"` you can use `(CON_UNKNOWN, 1)` in your config. It's what the strings would be parsed to.

**Comment by mahkoh** [comment]
Also please report this to Nvidia.

**Comment by nabajour** [comment]
> Instead of `"Unknown-1"` you can use `(CON_UNKNOWN, 1)` in your config. It's what the string would be parsed to.

Thanks, this fixes the "get_connector" issue and the complaining in the logs!


> Also please report this to Nvidia.

not sure what to report on the nvidia side. You expect it to report DRM_MODE_CONNECTOR_USB on the DRM side instead of DRM_MODE_CONNECTOR_Unknown for my setup? Does jay just acts as a pass-through w.r.t. DRM driver for this ?

**Comment by mahkoh** [comment]
I don't know what the correct type is. I assume that it is either _USB or _DP since USB-C can be used to tunnel a display port connection.

Jay just reports what the DRM subsystem reports and in this case `/sys/class/drm` shows that the kernel also doesn't understand the type.

Nvidia should report one of the defined connector types instead of unknown.

**Comment by mahkoh** [comment]
I don't believe there is anything left to do here.

**Comment by nabajour** [comment]
For reference, I posted this to [the NVidia forum](https://forums.developer.nvidia.com/t/usb-c-graphics-card-output-identified-as-unknown/308650)
