### ISSUE TITLE
some games doesn't pick the full resolution of the game or resize isn't correct

### ISSUE THREAD

**Issue by NextWork123** [mahkoh/jay#321]
Hello, as the title describe some games under proton seem doesn't let me to put 2560x1440 resolution and it resize uncorrect i gonna put a pics for see the issue.
![jay](https://github.com/user-attachments/assets/f12055d3-e90e-4f19-88b1-f76a4004316e)

Best Regards,
NextWorks

**Comment by mahkoh** [comment]
Can you test with sway or some other compositors?

**Comment by NextWork123** [comment]
> Can you test with sway or some other compositors?

i was thinking it can be because it is an xwayland window so jay act weird?

**Comment by mahkoh** [comment]
Assuming that the `XEC` monitor is in the center, you probably want to set `x = 2560` for the `HWP` monitor and leave `y = 0`.

**Comment by NextWork123** [comment]
> Assuming that the `XEC` monitor is in the center, you probably want to set `x = 2560` for the `HWP` monitor and leave `y = 0`.

with that setting i have the inverse result i can cross the cursor right to the monitor and it goes to the other monitor instead i want to cross the monitor in the left side

**Comment by mahkoh** [comment]
Then set `x = 1920` for the other monitor.

**Comment by NextWork123** [comment]
> Then set `x = 1920` for the other monitor.

ok thanks is working now! :)
