### ISSUE TITLE
More User Friendly Xkb Settings

### ISSUE THREAD

**Issue by vccrurial** [mahkoh/jay#327]
in jay it looks harder to setup this. in other compositors like sway and hyprland there are options like (x)kb_layout and (x)kb_options. in my case I'm trying to replicate these hyprland's config lines in jay:

kb_layout = us,ru
kb_options = grp:win_space_toggle, compose:ralt

and didn't managed yet.

(sorry if issue tracker is not suitable for posting this, feel free to delete)

**Comment by mahkoh** [comment]
You can use setxkbmap to get the complete layout

```
~$ setxkbmap -print -layout us,ru -option grp:win_space_toggle -option compose:ralt
WARNING: Running setxkbmap against an Xwayland server
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+ru:2+inet(evdev)+compose(ralt)+group(win_space_toggle):1+group(win_space_toggle):2"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```
