### ISSUE TITLE
Jay does not start

### ISSUE THREAD

**Issue by Aarrayy** [mahkoh/jay#334]
Hey mahkoh, i recently wanted to try jay and i encountered that it refuses to start. my GPU does not support the vulkan wayland due to a missing feature set but it should work fine with OpenGL as Hyprland and SwayWM do. What do you think? i think i have support for atomic modesetting but for some reason jay doesn't seem to pick it up? i uploaded the jay log below.

[jay-2024-12-24T14:26:13.948Z-0.txt](https://github.com/user-attachments/files/18240362/jay-2024-12-24T14.26.13.948Z-0.txt)

GPU: AMD R7 370 4GB (GCN 1)

Thanks in advance.

**Comment by mahkoh** [comment]
>Could not initialize drm device: Could not enable atomic modesetting: Operation not supported (os error 95)

Are you sure that your driver supports atomic modesetting? I know that sway supports legacy modesetting but Jay does not.

**Comment by Shendisx** [comment]
i'm not 100% sure if it does. I wonder if Hyprland falls back to the legacy modesetting when it's not supported. i'll investigate and report after.

**Comment by Shendisx** [comment]
Well it seems that either my GPU does not support it or amdgpu broke it in recent updates. Sorry for the inconvenience. Closing.

**Comment by mahkoh** [comment]
If you using an old AMD GPU you can try manually enabling the AMDGPU driver for it: https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

**Comment by Supded** [comment]
No, it's a gen 3 intel iGPU. I'll try to force it by i915.nuclear_pageflip=1

**Comment by Supded** [comment]
I got some progress, jay starts with a black screen, it was just frozen tty buffer before. 

[jaylog.log](https://github.com/user-attachments/files/19526223/jaylog.log)

**Comment by mahkoh** [comment]
The log output says that the opengl driver doesn't support modifiers but at least the Intel crocus driver should always support modifiers.

**Comment by Supded** [comment]
It is i915g, not crocus. Modifiers is tiling? My graphics buffer is x tiled in other compositors.

**Comment by mahkoh** [comment]
It looks like i915g doesn't support modifiers. Sway always pretends that KMS supports the invalid modifier and that egl supports the linear modifiers so it works out there.

**Comment by Supded** [comment]
Sorry for being annoying, maybe I misunderstand something. My output is not linear, kmsgrab screenshot - 
![Image](https://github.com/user-attachments/assets/381381f7-00e1-4d68-912b-d42c659e0910)
[kmsgrab @ 0x5b615da12740] Template framebuffer is 50: 1680x1050 format 34325258 modifier 100000000000001 flags 2.
and drm_info reports I915_FORMAT_MOD_X_TILED (0x0100000000000001) 
[drminfo.log](https://github.com/user-attachments/files/19526902/drminfo.log)
You mean some other modifiers? Please, explain.
