### ISSUE TITLE
[Question] Failed to compile.

### ISSUE THREAD

**Issue by ahmadraniri1994** [mahkoh/jay#36]
Hello, glad I found your project, today I'm trying to compile `jay` but I got this error : 
```
error: where clause not allowed here
  --> src/utils/windows.rs:14:62
   |
14 |     type Windows<'a, const N: usize> = WindowsIter<'a, T, N> where T: 'a;
   |                                     -                        ^^^^^^^^^^^
   |                                     |
   |                                     help: move it here: `where T: 'a`

error: could not compile `jay` due to previous error
```
is it because my rust and cargo not quite new ?
- my rustc : 
```
Package: rustc
Version: 1.59.0+dfsg1-1
```
- my cargo : 
```
Package: cargo
Version: 0.57.0-7+b1

```

**Comment by mahkoh** [comment]
Thanks for your interest. Please upgrade to the latest stable rustc version: 1.61.0. The syntax suggested by the error message you're getting has been deprecated in 1.61.0 and replaced by the new syntax that the code is currently using.

**Comment by ahmadraniri1994** [comment]
Thanks @mahkoh , I'm on my way to upgrade it, thanks.
