### ISSUE TITLE
layer-shell-protocol support.

### ISSUE THREAD

**Issue by ahmadraniri1994** [mahkoh/jay#43]
I see [jay](https://github.com/mahkoh/jay) still not fully supports layer shell protocol (I hope I'm correct) which allow external bar to preserve its own space, so when window is tiled, external bar's space won't be overwritten by tiled window or otherwise. I'll be back with some illustration.

**Comment by ahmadraniri1994** [comment]
before window is tiled : 
![2022-06-12T14:53:44,187952582+07:00](https://user-images.githubusercontent.com/72283174/173223177-87c7c429-32d1-41a4-be38-c3745172c789.png)

when window is tiled :  
![2022-06-12T14:54:22,148807473+07:00](https://user-images.githubusercontent.com/72283174/173223253-e08c079f-725a-4c78-8e37-a61ea4bc83d1.png)

The tiled window covers the bar (waybar).

**Comment by mahkoh** [comment]
Yes, as documented in https://github.com/mahkoh/jay/issues/8, exclusive zones are not yet implemented. This should not be too hard but I'm currently working on other stuff.
