### ISSUE TITLE
Clipboard causes Firefox to crash

### ISSUE THREAD

**Issue by uncomfyhalomacro** [mahkoh/jay#47]
Trying to `Ctrl+C` to copy some whatever stuff in Firefox (flatpak) browser crashes the browser.

**Comment by mahkoh** [comment]
This is a bug in GTK3: https://gitlab.gnome.org/GNOME/gtk/-/issues/5097

In the meantime I might be able to gracefully work around this particular problem in Jay. I'll look at it later.

**Comment by mahkoh** [comment]
Should be fixed on master.

**Comment by uncomfyhalomacro** [comment]
Thanks! Will test out later
