### ISSUE TITLE
Change keyboard layout to german

### ISSUE THREAD

**Issue by Hirschiii** [mahkoh/jay#54]
Hi, nice Project!

I just don't know how to change the keyboard-layout. I saw you just created your own, custom layout. Do I have to do this for the german default one as well?

Thank you very much :)

Hirschiii

**Comment by mahkoh** [comment]
You can write it yourself or you can use xkbcomp to generate it for you:

```
xkbcomp -xkb - keymap.xkb <<EOF
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+de(basic)"        };
};
EOF
```
