### ISSUE TITLE
Add single, final shaders to context.

### ISSUE THREAD

**Issue by sigma-957** [mahkoh/jay#55]
If I understand correctly, currently the "internal" texture runs through the "solid" and "alpha" shaders, and the borders and bar go through "fill".  I would like to be able to apply color correction (or whatever else, blur, etc.) to the entire display without touching those shaders separately (actually in the case of things like blur one needs the coordinates in the fragment shader, too).  I have screwed around implementing this myself, but I haven't quite figured out how to best accomplish it.

Smashing work on this.

**Comment by sigma-957** [comment]
I see now after some tinkering that my previous understanding of the shader implementation was wrong, however it's still desirable to have one single shader that covers the entire physical display.

**Comment by mahkoh** [comment]
Applying an effect to the entire framebuffer should be relatively easy. The only thing to consider is whether you want to apply this effect after the cursor has been rendered (in case software cursors are used) or before.

Applying a blur effect to individual windows would be much harder. Windows can contain sub-surfaces and currently we just render them from back to front directly to the framebuffer. If we wanted to correctly apply a blur effect, we would have to first render the entire window to a temporary texture and then apply the blur effect to that texture.

**Comment by sigma-957** [comment]
Software cursors should be subject to the stack of effects (in case you warp texture coordinates, you'd want the cursor to follow those).

I've gotten fairly decent results from making edits to the tex-alpha.frag and symlinking it to the non-alpha shader, but each container then applies this to the coords within the container's borders.  So, it's fine if you only have one container, which is how I've been using it for e.g. mpv.

**Comment by sigma-957** [comment]
Sorry to necrobump this, but what if any solution was there?  It's totally fine if this ended up being a _won't implement_, but I'm also not discounting that I might not be skillful enough to spot a solution were it implemented.

**Comment by mahkoh** [comment]
Nothing has changed in this regard since you opened this issue.
