### ISSUE TITLE
Changing the colors?

### ISSUE THREAD

**Issue by Vixeliz** [mahkoh/jay#58]
Hello! Love this project I've been looking for a customizable rust wayland wm and this fits the bill. I started working on my config and its going mostly well. One thing though is I can't figure out how to change the titlebar colors for example or even possibly disabling them? I looked through the jay-config docs and noticed the themes module but it seems like the colors are hardcoded? I'm most likely missing smth. Thanks for your awesome work!

Edit: One other question too. Is there any way to resize windows with keyboard keys? I like resizing with mod+ctrl+hjkl it would be nice if that was possible

**Comment by Vixeliz** [comment]
As for setting the color as a temporary fix I added a function to src/theme.rs:
```rust
pub fn set_color(colorable: Colorable, color: Color) {
    get!().set_color(colorable, color);
}
```

**Comment by mahkoh** [comment]
You can use the method on Colorable: https://mahkoh.github.io/jay/jay_config/theme/colors/struct.Colorable.html#method.set_color

**Comment by Vixeliz** [comment]
> You can use the method on Colorable: https://mahkoh.github.io/jay/jay_config/theme/colors/struct.Colorable.html#method.set_color

Thanks I see, I think a set_color function for consistency would be nice

**Comment by mahkoh** [comment]
There are now freestanding functions.
