### ISSUE TITLE
Remove bincode dependency

### ISSUE THREAD

**Issue by mahkoh** [mahkoh/jay#62]
These guys have managed to release 3 release candidates of 2.0 in as many years with no resolution in sight and with the upgrade to rc3 forcing me to look into what changed.

**Comment by romanstingler** [comment]
Zero-copy deserialization framework for Rust
https://github.com/rkyv/rkyv

**Comment by mahkoh** [comment]
rkyv does not support backwards compatibility and is therefore not suitable for this usecase: https://github.com/rkyv/rkyv/issues/393#issuecomment-1885059328
