### ISSUE TITLE
Fail to open wezterm

### ISSUE THREAD

**Issue by lengyijun** [mahkoh/jay#67]

**Comment by mahkoh** [comment]
This is a bug in wezterm. If the configured window size is too small, wezterm calculates calculates a window size 0 and then never attaches a buffer:

```rust
        if config.width > 0 && config.height > 0 {
            // Avoid reconfiguring with a 0 sized surface, as webgpu will
            // panic in that case
            // <https://github.com/wez/wezterm/issues/2881>
            self.surface.configure(&self.device, &config);
        }
```

Instead, wezterm should always respect the surface size requested by the compositor.
