### ISSUE TITLE
protocol: add ext_session_lock_manager_v1

### ISSUE THREAD

**Issue by uncomfyhalomacro** [mahkoh/jay#70]

**Comment by mahkoh** [comment]
This protocol is already supported but only for privileged applications. Start the application with `jay run-privileged <program>` to give it access to the protocol.

**Comment by junelva** [comment]
Fwiw, while `jay run-privileged` works on the command line, `privileged = true` in a shortcut definition does not work for me. This is an example of how it can be done using the command.

```
alt-shift-p = { type = "exec", exec = ["jay", "run-privileged", "swaylock", "--", "-c", "000000"] }
```

**Comment by mahkoh** [comment]
Are you sure that 

```toml
alt-shift-p = { type = "exec", exec = { prog = "swaylock", args = ["-c", "000000"], privileged = true } }
```

does not work?

**Comment by junelva** [comment]
Ah, I see. That does work. There is something in my head that is missing which makes the notation you used here not obvious to me. I understand Rust structures, so toml is readable, but I didn't know how to find out that args needed to be a bracketed list. Thanks!
